version: '3.9'
services:
  app:
    container_name: laravel_app
    build: .
    volumes:
      - laravel_app_data:/var/www/html
    expose:
      - "9000"
    networks:
      - laravel_network

  web:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - laravel_app_data:/var/www/html:ro
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laravel_network

  db:
    image: mysql:8
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  laravel_app_data:
  db_data:

networks:
  laravel_network:
